### ISSUE TITLE
Update the image

### ISSUE THREAD

**Issue by williamdes** [legendu-net/docker-rustpython#7]
Could you please update the Docker image or remove it ?

**Comment by dclong** [comment]
Thank you for your feedback. I've updated the Docker image and have scheduled it to be auto built monthly.

**Comment by williamdes** [comment]
Thank you!

**Comment by williamdes** [comment]
I will probably contribute another variant using the base rust image and alpine. Hope that's okay?

**Comment by dclong** [comment]
Sure. Contribution is greatly welcome!
